name: hourly-taxi-demand-feature-pipeline

on:
  schedule:
    - cron: '0 * * * *'

jobs:
  feature_pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Poetry
      uses: snok/install-poetry@v1

    - name: Cache Poetry packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/pypoetry
          ~/.venv
        key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          ${{ runner.os }}-poetry-

    - name: Install Dependencies
      run: poetry install

    - name: Execute Python workflows from bash script
      env:
        HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
      run: poetry run jupyter nbconvert --to notebook --execute notebooks/12_feature_pipelin.ipynb
